### ISSUE TITLE
[Discussion] Question regarding the video demo image

### ISSUE THREAD

**Issue by HolmesShuan** [wangjiangshan0725/RF-Solver-Edit#8]
Hi, I enjoyed reading your paper—it’s a good idea with promising results.
I have a minor question about the demo image showcasing the results of video editing. Why do the clothes change in response to the prompt “African …”?

**Comment by wangjiangshan0725** [comment]
Thanks for your interest in our work! The prompts presented in the paper are reduced to retain only the most essential parts (because the complete prompts are too long to be presented in the figure of our paper). The prompt actually used in the experiment for African woman is "a close-up shot of a african woman standing in a dimly lit room. she is wearing a traditional african outfit, which includes a yellow dress with intricate designs and a matching bonnet. the woman has her hair adorned with a silver accessory. she is looking directly at the camera with a neutral expression."

**Comment by HolmesShuan** [comment]
Sounds reasonable.

**Comment by wangjiangshan0725** [comment]
@HolmesShuan Settting the feature sharing step to 0, then the results is solely produced by RF-solver alone.

**Comment by HolmesShuan** [comment]
Cool
